# Generated by Django 4.0.5 on 2022-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(height_field=100, upload_to='portfolio/images/', width_field=100),
        ),
    ]
